LIBRARY_PATH = "../library/"
SECRET_KEY = "=JbX0gvs3ivIZkST+HI"
SQLALCHEMY_DATABASE_URI = "sqlite:///../library.db"
BOOKS_PER_PAGE = 5
EBOOK_EXTENSIONS = ('epub', 'pdf')
WRITE_META_ON_SAVE = True
ADD_SERIES_TO_META_TITLE = True
